version: "3"
services:
  pgsql:
    image: postgres:11
    ports:
      - "5000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - pgsql
    restart: always

  

networks:
  pgsql: